Repository meilisearch/docs-scraper, pull requests merged in 2023-06, with the labels that each got.

#387 Feature/add analytics
  .github/scripts/check-release.sh
  .github/workflows/publish-docker-image.yml
  scraper/src/config/config_loader.py
  scraper/src/config/version.py
  scraper/src/meilisearch_helper.py
  tests/config_loader/basic_test.py
  tests/meilisearch_helper/__init__.py
  tests/meilisearch_helper/common.py
  tests/meilisearch_helper/meilisearch_helper_test.py
  tests/meilisearch_helper/version_test.py
Labels: enhancement

#394 Reduce docker image size
  .dockerignore
  Dockerfile
Labels: maintenance

#401 Add back chromedriver tests
  .github/workflows/tests.yml
  scraper/src/js_executor.py
  tests/config_loader/get_extra_facets_test.py
  tests/config_loader/open_selenium_browser_test.py
  tests/config_loader/start_urls_test.py
Labels: skip-changelog

#403 Add Meilisearch Cloud touchpoint in README.md section
  README.md
Labels: skip-changelog
